version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - realestate-net
    env_file:
      - ./app/.env  # ✅ ahora se activan las variables del .env

  db:  # ❌ Desactiva este servicio si vas a usar RDS real (opcional)
    image: postgres:15
    environment:
      POSTGRES_DB: realestate
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: realhermes88
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - realestate-net

volumes:
  pgdata:

networks:
  realestate-net:
